//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSAutenticador
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Credenciales", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class Credenciales : object
    {

        private string ContrasenaEncriptadaField;

        private string UsuarioEncriptadoField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContrasenaEncriptada
        {
            get
            {
                return this.ContrasenaEncriptadaField;
            }
            set
            {
                this.ContrasenaEncriptadaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioEncriptado
        {
            get
            {
                return this.UsuarioEncriptadoField;
            }
            set
            {
                this.UsuarioEncriptadoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResultadoAutenticacion", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class ResultadoAutenticacion : object
    {

        private string MensajeField;

        private bool ResultadoField;

        private int TipoUsuarioField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoUsuario
        {
            get
            {
                return this.TipoUsuarioField;
            }
            set
            {
                this.TipoUsuarioField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UsuarioRegistro", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class UsuarioRegistro : object
    {

        private string ContrasenaField;

        private string EmailField;

        private string IdentificacionField;

        private string NombreField;

        private string PrimerApellidoField;

        private string SegundoApellidoField;

        private int TipoField;

        private string UsuarioField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena
        {
            get
            {
                return this.ContrasenaField;
            }
            set
            {
                this.ContrasenaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResultadoRegistro", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class ResultadoRegistro : object
    {

        private bool ExitosoField;

        private string MensajeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso
        {
            get
            {
                return this.ExitosoField;
            }
            set
            {
                this.ExitosoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "WSAutenticador.IServicioAutenticacion")]
    public interface IServicioAutenticacion
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioAutenticacion/ValidarLogin", ReplyAction = "http://tempuri.org/IServicioAutenticacion/ValidarLoginResponse")]
        System.Threading.Tasks.Task<WSAutenticador.ResultadoAutenticacion> ValidarLoginAsync(WSAutenticador.Credenciales credenciales);

        //AdminUsuarios
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioAutenticacion/RegistrarUsuario", ReplyAction = "http://tempuri.org/IServicioAutenticacion/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<WSAutenticador.ResultadoRegistro> RegistrarUsuarioAsync(WSAutenticador.UsuarioRegistro usuario);
        [System.ServiceModel.OperationContractAttribute(
    Action = "http://tempuri.org/IServicioAutenticacion/ObtenerUsuarios",
    ReplyAction = "http://tempuri.org/IServicioAutenticacion/ObtenerUsuariosResponse")]
        System.Threading.Tasks.Task<WSAutenticador.UsuarioRegistro[]> ObtenerUsuariosAsync();

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://tempuri.org/IServicioAutenticacion/EditarUsuario",
            ReplyAction = "http://tempuri.org/IServicioAutenticacion/EditarUsuarioResponse")]
        System.Threading.Tasks.Task<WSAutenticador.ResultadoRegistro> EditarUsuarioAsync(WSAutenticador.UsuarioRegistro usuario);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://tempuri.org/IServicioAutenticacion/ActivarUsuario",
            ReplyAction = "http://tempuri.org/IServicioAutenticacion/ActivarUsuarioResponse")]
        System.Threading.Tasks.Task<WSAutenticador.ResultadoRegistro> ActivarUsuarioAsync(string identificacion);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://tempuri.org/IServicioAutenticacion/InactivarUsuario",
            ReplyAction = "http://tempuri.org/IServicioAutenticacion/InactivarUsuarioResponse")]
        System.Threading.Tasks.Task<WSAutenticador.ResultadoRegistro> InactivarUsuarioAsync(string identificacion);
        //AdminUsuarios
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServicioAutenticacionChannel : WSAutenticador.IServicioAutenticacion, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioAutenticacionClient : System.ServiceModel.ClientBase<WSAutenticador.IServicioAutenticacion>, WSAutenticador.IServicioAutenticacion
    {

        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public ServicioAutenticacionClient() :
                base(ServicioAutenticacionClient.GetDefaultBinding(), ServicioAutenticacionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServicioAutenticacionClient(EndpointConfiguration endpointConfiguration) :
                base(ServicioAutenticacionClient.GetBindingForEndpoint(endpointConfiguration), ServicioAutenticacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServicioAutenticacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(ServicioAutenticacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServicioAutenticacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(ServicioAutenticacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServicioAutenticacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<WSAutenticador.ResultadoAutenticacion> ValidarLoginAsync(WSAutenticador.Credenciales credenciales)
        {
            return base.Channel.ValidarLoginAsync(credenciales);
        }

        //AdminUsuario
        public System.Threading.Tasks.Task<WSAutenticador.UsuarioRegistro[]> ObtenerUsuariosAsync()
        {
            return base.Channel.ObtenerUsuariosAsync();
        }

        public System.Threading.Tasks.Task<WSAutenticador.ResultadoRegistro> EditarUsuarioAsync(WSAutenticador.UsuarioRegistro usuario)
        {
            return base.Channel.EditarUsuarioAsync(usuario);
        }

        public System.Threading.Tasks.Task<WSAutenticador.ResultadoRegistro> ActivarUsuarioAsync(string identificacion)
        {
            return base.Channel.ActivarUsuarioAsync(identificacion);
        }

        public System.Threading.Tasks.Task<WSAutenticador.ResultadoRegistro> InactivarUsuarioAsync(string identificacion)
        {
            return base.Channel.InactivarUsuarioAsync(identificacion);
        }

        public System.Threading.Tasks.Task<WSAutenticador.ResultadoRegistro> RegistrarUsuarioAsync(WSAutenticador.UsuarioRegistro usuario)
        {
            return base.Channel.RegistrarUsuarioAsync(usuario);
        }
        //AdminUsurios

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
#endif

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:51087/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioAutenticacionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioAutenticacionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion);
        }

        public enum EndpointConfiguration
        {

            BasicHttpBinding_IServicioAutenticacion,
        }
    }
} 