//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetiroRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio.Entities")]
    public partial class RetiroRequest : object
    {
        
        private string CvvField;
        
        private string FechaVencimientoField;
        
        private string IdComercioOCajeroField;
        
        private decimal MontoField;
        
        private string NombreClienteField;
        
        private string NumeroTarjetaField;
        
        private string PinField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvv
        {
            get
            {
                return this.CvvField;
            }
            set
            {
                this.CvvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaVencimiento
        {
            get
            {
                return this.FechaVencimientoField;
            }
            set
            {
                this.FechaVencimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdComercioOCajero
        {
            get
            {
                return this.IdComercioOCajeroField;
            }
            set
            {
                this.IdComercioOCajeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTarjeta
        {
            get
            {
                return this.NumeroTarjetaField;
            }
            set
            {
                this.NumeroTarjetaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin
        {
            get
            {
                return this.PinField;
            }
            set
            {
                this.PinField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetiroResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio.Entities")]
    public partial class RetiroResponse : object
    {
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio.Entities")]
    public partial class ConsultaRequest : object
    {
        
        private string CvvField;
        
        private string FechaVencimientoField;
        
        private string IdComercioOCajeroField;
        
        private string NumeroTarjetaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvv
        {
            get
            {
                return this.CvvField;
            }
            set
            {
                this.CvvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaVencimiento
        {
            get
            {
                return this.FechaVencimientoField;
            }
            set
            {
                this.FechaVencimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdComercioOCajero
        {
            get
            {
                return this.IdComercioOCajeroField;
            }
            set
            {
                this.IdComercioOCajeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTarjeta
        {
            get
            {
                return this.NumeroTarjetaField;
            }
            set
            {
                this.NumeroTarjetaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio.Entities")]
    public partial class ConsultaResponse : object
    {
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        private string SaldoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Saldo
        {
            get
            {
                return this.SaldoField;
            }
            set
            {
                this.SaldoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CambioPinRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio.Entities")]
    public partial class CambioPinRequest : object
    {
        
        private string CvvField;
        
        private string FechaVencimientoField;
        
        private string IdComercioOCajeroField;
        
        private string NumeroTarjetaField;
        
        private string PinActualField;
        
        private string PinNuevoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvv
        {
            get
            {
                return this.CvvField;
            }
            set
            {
                this.CvvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaVencimiento
        {
            get
            {
                return this.FechaVencimientoField;
            }
            set
            {
                this.FechaVencimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdComercioOCajero
        {
            get
            {
                return this.IdComercioOCajeroField;
            }
            set
            {
                this.IdComercioOCajeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTarjeta
        {
            get
            {
                return this.NumeroTarjetaField;
            }
            set
            {
                this.NumeroTarjetaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinActual
        {
            get
            {
                return this.PinActualField;
            }
            set
            {
                this.PinActualField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinNuevo
        {
            get
            {
                return this.PinNuevoField;
            }
            set
            {
                this.PinNuevoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CambioPinResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio.Entities")]
    public partial class CambioPinResponse : object
    {
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Retiro", ReplyAction="http://tempuri.org/IService/RetiroResponse")]
        System.Threading.Tasks.Task<ServiceReference2.RetiroResponse> RetiroAsync(ServiceReference2.RetiroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Consulta", ReplyAction="http://tempuri.org/IService/ConsultaResponse")]
        System.Threading.Tasks.Task<ServiceReference2.ConsultaResponse> ConsultaAsync(ServiceReference2.ConsultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CambioPin", ReplyAction="http://tempuri.org/IService/CambioPinResponse")]
        System.Threading.Tasks.Task<ServiceReference2.CambioPinResponse> CambioPinAsync(ServiceReference2.CambioPinRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServiceChannel : ServiceReference2.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ServiceReference2.IService>, ServiceReference2.IService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.RetiroResponse> RetiroAsync(ServiceReference2.RetiroRequest request)
        {
            return base.Channel.RetiroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.ConsultaResponse> ConsultaAsync(ServiceReference2.ConsultaRequest request)
        {
            return base.Channel.ConsultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.CambioPinResponse> CambioPinAsync(ServiceReference2.CambioPinRequest request)
        {
            return base.Channel.CambioPinAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64771/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
