//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsolaPrueba.WCFRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetiroRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio.Entities")]
    [System.SerializableAttribute()]
    public partial class RetiroRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CvvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdComercioOCajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvv {
            get {
                return this.CvvField;
            }
            set {
                if ((object.ReferenceEquals(this.CvvField, value) != true)) {
                    this.CvvField = value;
                    this.RaisePropertyChanged("Cvv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaVencimientoField, value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdComercioOCajero {
            get {
                return this.IdComercioOCajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.IdComercioOCajeroField, value) != true)) {
                    this.IdComercioOCajeroField = value;
                    this.RaisePropertyChanged("IdComercioOCajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTarjeta {
            get {
                return this.NumeroTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTarjetaField, value) != true)) {
                    this.NumeroTarjetaField = value;
                    this.RaisePropertyChanged("NumeroTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin {
            get {
                return this.PinField;
            }
            set {
                if ((object.ReferenceEquals(this.PinField, value) != true)) {
                    this.PinField = value;
                    this.RaisePropertyChanged("Pin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetiroResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio.Entities")]
    [System.SerializableAttribute()]
    public partial class RetiroResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio.Entities")]
    [System.SerializableAttribute()]
    public partial class ConsultaRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CvvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdComercioOCajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTarjetaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvv {
            get {
                return this.CvvField;
            }
            set {
                if ((object.ReferenceEquals(this.CvvField, value) != true)) {
                    this.CvvField = value;
                    this.RaisePropertyChanged("Cvv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaVencimientoField, value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdComercioOCajero {
            get {
                return this.IdComercioOCajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.IdComercioOCajeroField, value) != true)) {
                    this.IdComercioOCajeroField = value;
                    this.RaisePropertyChanged("IdComercioOCajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTarjeta {
            get {
                return this.NumeroTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTarjetaField, value) != true)) {
                    this.NumeroTarjetaField = value;
                    this.RaisePropertyChanged("NumeroTarjeta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio.Entities")]
    [System.SerializableAttribute()]
    public partial class ConsultaResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((object.ReferenceEquals(this.SaldoField, value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CambioPinRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio.Entities")]
    [System.SerializableAttribute()]
    public partial class CambioPinRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CvvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdComercioOCajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinNuevoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvv {
            get {
                return this.CvvField;
            }
            set {
                if ((object.ReferenceEquals(this.CvvField, value) != true)) {
                    this.CvvField = value;
                    this.RaisePropertyChanged("Cvv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaVencimientoField, value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdComercioOCajero {
            get {
                return this.IdComercioOCajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.IdComercioOCajeroField, value) != true)) {
                    this.IdComercioOCajeroField = value;
                    this.RaisePropertyChanged("IdComercioOCajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTarjeta {
            get {
                return this.NumeroTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTarjetaField, value) != true)) {
                    this.NumeroTarjetaField = value;
                    this.RaisePropertyChanged("NumeroTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinActual {
            get {
                return this.PinActualField;
            }
            set {
                if ((object.ReferenceEquals(this.PinActualField, value) != true)) {
                    this.PinActualField = value;
                    this.RaisePropertyChanged("PinActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinNuevo {
            get {
                return this.PinNuevoField;
            }
            set {
                if ((object.ReferenceEquals(this.PinNuevoField, value) != true)) {
                    this.PinNuevoField = value;
                    this.RaisePropertyChanged("PinNuevo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CambioPinResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio.Entities")]
    [System.SerializableAttribute()]
    public partial class CambioPinResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFRef.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Retiro", ReplyAction="http://tempuri.org/IService/RetiroResponse")]
        ConsolaPrueba.WCFRef.RetiroResponse Retiro(ConsolaPrueba.WCFRef.RetiroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Retiro", ReplyAction="http://tempuri.org/IService/RetiroResponse")]
        System.Threading.Tasks.Task<ConsolaPrueba.WCFRef.RetiroResponse> RetiroAsync(ConsolaPrueba.WCFRef.RetiroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Consulta", ReplyAction="http://tempuri.org/IService/ConsultaResponse")]
        ConsolaPrueba.WCFRef.ConsultaResponse Consulta(ConsolaPrueba.WCFRef.ConsultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Consulta", ReplyAction="http://tempuri.org/IService/ConsultaResponse")]
        System.Threading.Tasks.Task<ConsolaPrueba.WCFRef.ConsultaResponse> ConsultaAsync(ConsolaPrueba.WCFRef.ConsultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CambioPin", ReplyAction="http://tempuri.org/IService/CambioPinResponse")]
        ConsolaPrueba.WCFRef.CambioPinResponse CambioPin(ConsolaPrueba.WCFRef.CambioPinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CambioPin", ReplyAction="http://tempuri.org/IService/CambioPinResponse")]
        System.Threading.Tasks.Task<ConsolaPrueba.WCFRef.CambioPinResponse> CambioPinAsync(ConsolaPrueba.WCFRef.CambioPinRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ConsolaPrueba.WCFRef.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ConsolaPrueba.WCFRef.IService>, ConsolaPrueba.WCFRef.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsolaPrueba.WCFRef.RetiroResponse Retiro(ConsolaPrueba.WCFRef.RetiroRequest request) {
            return base.Channel.Retiro(request);
        }
        
        public System.Threading.Tasks.Task<ConsolaPrueba.WCFRef.RetiroResponse> RetiroAsync(ConsolaPrueba.WCFRef.RetiroRequest request) {
            return base.Channel.RetiroAsync(request);
        }
        
        public ConsolaPrueba.WCFRef.ConsultaResponse Consulta(ConsolaPrueba.WCFRef.ConsultaRequest request) {
            return base.Channel.Consulta(request);
        }
        
        public System.Threading.Tasks.Task<ConsolaPrueba.WCFRef.ConsultaResponse> ConsultaAsync(ConsolaPrueba.WCFRef.ConsultaRequest request) {
            return base.Channel.ConsultaAsync(request);
        }
        
        public ConsolaPrueba.WCFRef.CambioPinResponse CambioPin(ConsolaPrueba.WCFRef.CambioPinRequest request) {
            return base.Channel.CambioPin(request);
        }
        
        public System.Threading.Tasks.Task<ConsolaPrueba.WCFRef.CambioPinResponse> CambioPinAsync(ConsolaPrueba.WCFRef.CambioPinRequest request) {
            return base.Channel.CambioPinAsync(request);
        }
    }
}
